### ISSUE TITLE
Diffing when managing multiple vlans is broken

### ISSUE THREAD

**Issue by b1naryth1ef** [Juniper/puppet-netdev-stdlib-junos#15]
When managing more than a single vlan, e.g.:

```puppet
netdev_vlan { "testvlan":
  vlan_id => 300,
  description => "This is a test.  Delete me."
}

netdev_vlan { "testvlan2":
  vlan_id => 5,
  description => "This is a test.  Delete me."
}
```

The diffing text displayed is incorrect when adding or removing more vlans, e.g. when adding testvlan2 you see the following on the first apply:

```
Notice: Compiled catalog for **************** in environment production in 2.86 seconds
Notice: /Stage[main]/Main/Node[****************]/Netdev_vlan[testvlan2]/vlan_id: vlan_id changed '300' to '5'
Notice: JUNOS:

[edit vlans]
+   testvlan2 {
+       vlan-id 5;
+   }

Notice: JUNOS: OK: COMMIT success!
```

After the initial apply the following happens on each subsequent run (without changes to the puppet code):
```
Notice: Compiled catalog for **************** in environment production in 2.83 seconds
Notice: /Stage[main]/Main/Node[****************]/Netdev_vlan[testvlan2]/vlan_id: vlan_id changed '300' to '5'
Error: JUNOS: Unmanaged VLAN interface:
Notice: JUNOS:


Notice: JUNOS: OK: COMMIT success!
```
Even though this causes a commit, no change is actually applied.

The expected behavior in both cases is correctly identifying that a new vlan is created, and not attempting to recreate/change a vlan subsequent to the apply.

**Comment by ganeshnalawade** [comment]
Please upgrade netdev_stdlib_junos module to latest version and check if you are still seeing this issue.
```
#puppet module upgrade juniper-netdev_stdlib_junos --version 2.0.1 
````

**Comment by b1naryth1ef** [comment]
Fixed, thanks!
